#!/usr/bin/env bash
xcode-select --install
sudo xcodebuild -license

pip3 install ansible
echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
source ~/.bashrc

if [ ! -d ~/ansible-starter/.git ]
then
    git clone https://github.com/unkrich/ansible-starter ~/ansible-starter
fi
cd ~/ansible-starter
git pull origin main --rebase

ansible-playbook local.yml --ask-become-pass --ask-vault-pass
