- name: Ensuring Homebrew Is Installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check
  tags:
    - homebrew
    - brew
    - install
    - macos

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ brew_cask_packages.dev }}"
    state: present
  register: result
  until: result is successful
  when: brew_cask_packages.dev is defined and homebrew_check.stat.exists

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ brew_packages.dev }}"
    state: present
  register: result
  until: result is successful
  when: brew_packages.dev is defined and homebrew_check.stat.exists
