- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"

- name: Add SSH Key to agent
  shell: ssh-add ~/.ssh/id_rsa

- name: Add GitHub to known hosts
  shell:
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    # - name: Check if Agent Forwarding is allowed
    # shell: grep -c "^AllowAgentForwarding yes" /etc/ssh/sshd_config || true
    # register: test_forwarding

    # - name: Allow Agent Forwarding
    # become: true
    # ansible.builtin.command: echo "AllowAgentForwarding yes" >> ~/.ssh/config
    # when: test_forwarding.stdout == "0"
